### ISSUE TITLE
Permute eq 2. code

### ISSUE THREAD

**Issue by aqibsaeed** [gstoica27/ZipIt#1]
Hi George, 

Thanks for open sourcing the code. Could you point/provide the code for `Permute (Eq. 2) ` as mentioned in Table 1?

**Comment by gstoica27** [comment]
Hi! 

Yes, you can find all our merging calculation functions in the "matching_functions.py" file - including the permute, which is [here](https://github.com/gstoica27/ZipIt/blob/65424b055e2c92e3e44ed39b79771f4f5fced406/matching_functions.py#L184).

Hope this helps!

**Comment by gstoica27** [comment]
Whoops, I accidentally marked this as "closed." Reopening just in case :)

**Comment by gstoica27** [comment]
Hi Professor Saeed,

I just wanted to follow up on this issue. Is there anything in addition I can answer? 

Thanks!

**Comment by aqibsaeed** [comment]
It is good, thanks!
