### ISSUE TITLE
[Question] ConvNeXt layers in MergeHandler

### ISSUE THREAD

**Issue by niklasnolte** [gstoica27/ZipIt#10]
I am trying to implement a graph for convnext, which has a custom module: LayerNorm2d. In there, the input is permuted before sent through LayerNorm. The mergehandler can use handle_layernorm for that right? no need to implement another function if I understand it right. That ties in with the question, if a torch.nn.Permute needs anything else but a "handle_fn" handler

**Comment by gstoica27** [comment]
Hi,

1. Yes the LayerNorm2d handler should already contain everything you need. 
2. For Permute, I believe it should look very similar to the handle_fn logic, except that you will further have to permute the dimensions of the merge/unmerge according to permutation defined in the module.

**Comment by niklasnolte** [comment]
1. you mean LayerNorm handler, right? there is no layernorm2d handler.
2. okay, i shall try that.

Thanks

**Comment by gstoica27** [comment]
For 1 - yes sorry. And 2 sounds good. Also, I just replied to your email as well about meeting :) Please let me know if I can help with anything else!
