### ISSUE TITLE
Apply on yolov5 models

### ISSUE THREAD

**Issue by www7890** [gstoica27/ZipIt#17]
Hi, gstoica27,
thanks to your implementation and code releasing. 
I am studying how to combine two well trained yolov5 models without any retrain or fine-tune.
Can this repo be applied on yolov5 models?  
thank you

**Comment by SeuXiao** [comment]
I'm sorry to bother you. I'm currently trying to combine two well trained yolo models into one model. Could you please tell me that if you have completed this? I saw you closed this issue on Aug 1.
