### ISSUE TITLE
a question about 'feature'

### ISSUE THREAD

**Issue by leondada** [gstoica27/ZipIt#2]
It seems that ZipIt relies on data, then I have a question:
1.  if there is no data, then the proposed ZipIt based on features seems unable to work? 
2.  if we have the data, why not train a new model directly?

**Comment by dbolya** [comment]
Hi, the data can be anything (not even the data you use to train) and it doesn't require labels. And you only need a small amount of data (see appendix in paper).

For any models using natural images, you could probably just take ~100 imagenet images and resize them down to your input image size and that would probably work as well as using the actual dataset itself. Feel free to test that though, if having access to the training dataset is an issue for you.

**Comment by gstoica27** [comment]
Hello! Just following up - is there anything in addition we can answer?

**Comment by leondada** [comment]
Thank you for your reply！
