### ISSUE TITLE
License Inquiry

### ISSUE THREAD

**Issue by bblakeslee-maker** [gstoica27/ZipIt#3]
I'm interesting in utilizing the ZipIt repository.  However, my organization's policy prevents me from utilizing code from repositories which do not bear a license file.  Would you be willing to apply an Apache or MIT license to the ZipIt repository?

Thank you for your consideration.

**Comment by gstoica27** [comment]
Hi! I just added an MIT license - hope this helps :) 

Closing for now, though please open if there is anything in addition!
