### ISSUE TITLE
zipit merging

### ISSUE THREAD

**Issue by nsaadati** [gstoica27/ZipIt#9]
Hi
Thanks for your well written paper and code
I run your cifar_resnet_training code and I trianed 10 resnet20*8 model and right now when I want to merge them using zipit_concept_merging code but I'm getting this error and I don't know why, Can you please help me with this?
(cuda version:11.1 and torch version=10.1)

python -m evaluation_scripts.zipit_concept_merging
match_tensors_zipit
Evaluating Pairs...:   0%|                                                                                                                                                                     | 0/4 [00:00<?, ?it/s]Files already downloaded and verified
50000it [00:00, 883736.96it/s]
50000it [00:00, 880656.77it/s]
Files already downloaded and verified
10000it [00:00, 883606.64it/s]
10000it [00:00, 875527.91it/s]
Preparing Models: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:09<00:00,  4.76s/it]
Resetting batch norm: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:07<00:00, 134.18it/s]
Resetting batch norm: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:07<00:00, 138.87it/s]
Forward Pass to Compute Merge Metrics: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:15<00:00, 63.55it/s]
Forward Pass to Compute Merge Metrics: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 995/1000 [00:15<00:00, 64.81it/s/home/exouser/ZipIt/matching_functions.py:84: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  col_idx = best_idx // sims.shape[1]
Computing transformations:  25%|█████████████████████████████████████▌                                                                                                                | 3/12 [00:00<00:01,  4.93it/s]
Resetting batch norm: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:13<00:00, 74.43it/s]
Evaluating model on CLIP class encodings:   0%|                                                                                                                                              | 0/200 [00:00<?, ?it/s]
Evaluating Pairs...:   0%|                                                                                                                                                                     | 0/4 [01:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/exouser/.conda/envs/cf/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/exouser/.conda/envs/cf/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/exouser/ZipIt/evaluation_scripts/zipit_concept_merging.py", line 129, in <module>
    run_node_experiment(
  File "/home/exouser/ZipIt/evaluation_scripts/zipit_concept_merging.py", line 82, in run_node_experiment
    results = evaluate_model(experiment_config['eval_type'], Merge, config)
  File "/home/exouser/ZipIt/utils.py", line 615, in evaluate_model
    acc_overall, acc_avg, perclass_acc = evaluate_cliphead_alltasks(
  File "/home/exouser/ZipIt/utils.py", line 219, in evaluate_cliphead_alltasks
    all_logits = torch.bmm(encodings, label_encodings.transpose(-1, -2)).transpose(1, 0)
RuntimeError: batch1 dim 2 must match batch2 dim 1

**Comment by nsaadati** [comment]
I tried another evaluation method provided in your code and changing it to this (experiment_config['eval_type']='logits') and it worked: this is the shape: encodings shape torch.Size([2, 50, 100])
label_encodings shape torch.Size([2, 50, 512])
I think the problem is I change another thing in your code because it was not working with output size be 512 when we are using cifar 100 and before changing it to this the code was actulay giving me errors:
if config['eval_type'] == 'logits':
        config['model']['output_dim'] = len(data['test']['class_names'])
    else:
        config['model']['output_dim'] = 100 #512
________________________________

**Comment by gstoica27** [comment]
Ah I see. Okay so the issue was that you had changed this:
`config['model']['output_dim'] = 512`
to this:
`config['model']['output_dim'] = 100 #512`

Which would cause errors as the CLIP label encoding dimension is 512. 

Is that a correct understanding? What was the error you were having before with CLIP? Or has that been resolved(?) - Anything I can help with?

**Comment by nsaadati** [comment]
if I make it 512 instead of 100 and with clip evl is still giving me error and it says the dim2 should be same as dim1 but it's [512] and [100], something like this error and I can share it with you later but my question is if we are using cifar100 why the output is 512?

________________________________

**Comment by gstoica27** [comment]
Yes please do. The reason for why the output is 512 is because in the CLIP setting, we are using the CLIP label encodings for the 100 cifar classes -- each of which is dimension 512. So we need our vision model to output a prediction of equal dimension to the CLIP encodings (i.e. 512) for classification.

**Comment by gstoica27** [comment]
I see - did you train your checkpoints with CLIP loss? 

From the error it looks like you instead trained them with standard classification (hence the linear weight having dim 100 instead of CLIPs 512). And the error is occurring because you're initializing a CLIP resnet20 but loading a non-clip resnet20 into it.

**Comment by nsaadati** [comment]
I'm not sure, but thanks for sharing the information.
